import {useState} from 'react';
import type {Row} from './workspace';
import {defaults,loadDraft,saveDraft,importDraft,validateDraft,configFromDraft} from './collector-config';
export default function CollectorSettings({rpc,baseUrl,devices,onDevices}:{rpc:(p:string,m?:string,b?:Row)=>Promise<any>,baseUrl:string,devices:Row[],onDevices:()=>void}){
 const [d,setD]=useState(()=>loadDraft(baseUrl)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const patch=(value:Partial<typeof d>)=>setD(previous=>({...previous,...value}));
 let validation='';try{validateDraft(d);}catch(e){validation=(e as Error).message;}
 const loopback=(()=>{try{return ['127.0.0.1','localhost','::1','[::1]'].includes(new URL(d.url).hostname);}catch{return false;}})();
 async function importFile(file?:File){if(!file)return;try{if(file.size>1024*1024)throw Error('Ayar dosyası 1 MB altında olmalı.');const next=importDraft(JSON.parse(await file.text()),baseUrl);setD(next);setMessage('Ayarlar içe aktarıldı. Dosyadaki token saklanmadı; indirmede güncel collector anahtarı kullanılır.');}catch(e){setMessage((e as Error).message);}}
 function persist(){try{saveDraft(baseUrl,d);setMessage('Taslak bu tarayıcıya kaydedildi. Master ayarları henüz değişmedi.');}catch(e){setMessage((e as Error).message);}}
 async function download(){setBusy(true);setMessage('');try{validateDraft(d);const v=await rpc('auth/collector-connection');const values=configFromDraft(d,v.collector_token);const link=URL.createObjectURL(new Blob([JSON.stringify(values,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=link;a.download='collector.json';a.click();setTimeout(()=>URL.revokeObjectURL(link),1000);try{saveDraft(baseUrl,d);}catch{}setMessage('collector.json indirildi. Master üzerinde mevcut dosyayı yedekle, yenisini yerleştir ve collector servisini yeniden başlat.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="collector-page collector-settings"><small>MASTER / VERİ TOPLAMA</small><h2>Master ayarları</h2><p>Bağlantıyı, sorumlu cihazları ve GPIO görevlerini tek ekrandan hazırla. Değişiklikler dosya master’a aktarıldığında uygulanır.</p>
 <div className="settings-actions"><label className="outline-button">Mevcut collector.json dosyasını aç<input aria-label="Collector ayar dosyasını aç" type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><button className="outline-button" onClick={persist} disabled={busy||!!validation}>Taslağı kaydet</button><button className="outline-button" onClick={()=>{setD(defaults(baseUrl));setMessage('Form varsayılanlara döndü; master ayarları değişmedi.');}}>Formu sıfırla</button></div>
 <fieldset disabled={busy} className="settings-sections">
 <section className="settings-card"><h3>1 · Bağlantı</h3><label className="field"><span>Master’ın erişeceği API adresi</span><input aria-label="Collector API adresi" value={d.url} onChange={e=>patch({url:e.target.value})}/></label>{loopback&&<p className="settings-warning">Bu adres master’ın kendisini gösterir. API başka bilgisayardaysa o bilgisayarın LAN / VPN adresini kullan.</p>}<label className="field"><span>Master adı</span><input value={d.worker} onChange={e=>patch({worker:e.target.value})}/></label><p>Node üzerindeki röle ve giriş eşleştirmelerinde aynı master adı kullanılmalı.</p></section>
 <section className="settings-card"><h3>2 · Okunacak cihazlar</h3><p>{d.ids.length?`${d.ids.length} cihaz seçili`:'Tüm aktif cihazlar: yeni cihazlar da bu master tarafından okunur.'}</p><input aria-label="Cihaz ara" placeholder="Cihaz adı veya ID ara" value={search} onChange={e=>setSearch(e.target.value)}/><div className="settings-actions"><button className="outline-button" onClick={()=>patch({ids:devices.map(x=>String(x.id))})}>Listelenenleri seç</button><button className="outline-button" onClick={()=>patch({ids:[]})}>Tüm aktif cihazları otomatik oku</button></div><div className="collector-devices">{devices.filter(x=>`${x.name} ${x.id}`.toLowerCase().includes(search.toLowerCase())).map(x=><label key={x.id}><input type="checkbox" checked={d.ids.includes(String(x.id))} onChange={e=>patch({ids:e.target.checked?[...d.ids,String(x.id)]:d.ids.filter(id=>id!==String(x.id))})}/><span>{x.name} · #{x.id}<small>{x.row?.ip||x.row?.protokol} · Unit {x.row?.slave_id??'—'}</small></span></label>)}{d.ids.filter(id=>!devices.some(x=>String(x.id)===id)).map(id=><p key={id}>Cihaz #{id} bu listede bulunamadı; kapsamda korunuyor. <button onClick={()=>patch({ids:d.ids.filter(x=>x!==id)})}>Kapsamdan çıkar</button></p>)}</div><button className="outline-button" onClick={onDevices}>Cihaz IP / port / profil ayarlarını aç</button><p>Birden fazla master varsa sorumluluk listelerini ayır. Boş liste hiçbir cihaz anlamına gelmez.</p></section>
 <section className="settings-card"><h3>3 · GPIO görevleri</h3><p><b>Çıkış röleyi yönetir. Giriş fiziksel sinyali okur.</b> Numara BCM numarasıdır; klemens veya röle sıra numarası değildir.</p><label className="account-toggle"><input type="checkbox" checked={d.commands} onChange={e=>patch({commands:e.target.checked,...(!e.target.checked?{gpio:false}:{})})}/>Komut yürütücüsü</label><div className="gpio-task"><label className="account-toggle"><input type="checkbox" checked={d.gpio} onChange={e=>patch({gpio:e.target.checked,...(e.target.checked?{commands:true}:{})})}/>Röle çıkışlarını etkinleştir</label>{d.gpio&&<label className="field"><span>Çıkış BCM izin listesi</span><input aria-label="GPIO çıkış pinleri" value={d.pins} onChange={e=>patch({pins:e.target.value})}/></label>}<p>Yalnızca kartta doğrulanmış çıkış pinlerini gir. Sonuç fiziksel kesici durumunu doğrulamaz.</p></div><div className="gpio-task"><label className="account-toggle"><input type="checkbox" checked={d.inputs} onChange={e=>patch({inputs:e.target.checked})}/>Dijital girişleri salt oku</label>{d.inputs&&<label className="field"><span>Giriş BCM izin listesi</span><input aria-label="GPIO giriş pinleri" value={d.inputPins} onChange={e=>patch({inputPins:e.target.value})}/></label>}<p>Pin yönü değişmez. Çıkış modundaki kanal “Giriş değil” görünür. Node panelinde giriş kanallarını ayrıca tanımla.</p></div></section>
 <details className="settings-card"><summary>4 · Gelişmiş okuma ayarları</summary><div className="field-row"><label className="field"><span>API zaman aşımı · sn</span><input type="number" min="1" max="3600" value={d.timeout} onChange={e=>patch({timeout:Number(e.target.value)})}/></label><label className="field"><span>Yapılandırma kontrolü · sn</span><input type="number" min="1" max="3600" value={d.refresh} onChange={e=>patch({refresh:Number(e.target.value)})}/></label></div><label className="field"><span>Okuma bloğundaki adres boşluğu</span><input type="number" min="0" max="124" value={d.gap} onChange={e=>patch({gap:Number(e.target.value)})}/></label><label className="field"><span>Terminal log özeti · sn</span><input type="number" min="0.1" max="3600" value={d.summary} onChange={e=>patch({summary:Number(e.target.value)})}/></label><label className="account-toggle"><input type="checkbox" checked={d.autoTag} onChange={e=>patch({autoTag:e.target.checked})}/>Mevcut collector otomatik tag seçeneğini etkinleştir</label><p>0 yalnızca bitişik registerları gruplar. Cihazın desteklediği adresler doğrulanmadan artırma.</p></details>
 </fieldset>
 <section className="settings-card"><h3>5 · Kesinti tamponu</h3><p>Ölçümler SQLite'a kaydedilir ve API'ye doğrulanmış batch olarak aktarılır. API kesilirse ölçümler korunur; komutlar tamponlanmaz.</p><label className="field"><span>Azami tampon ölçüm sayısı</span><input type="number" min="1000" max="10000000" value={d.bufferRows} onChange={e=>patch({bufferRows:Number(e.target.value)})}/></label><label className="field"><span>Yapılandırma önbelleği azami yaşı · saniye</span><input type="number" min="60" max="604800" value={d.cacheAge} onChange={e=>patch({cacheAge:Number(e.target.value)})}/></label><label className="field"><span>SQLite yolu · boşsa collector klasörü</span><input value={d.bufferPath} placeholder="Örn. /root/collector/measurements.sqlite3" onChange={e=>patch({bufferPath:e.target.value})}/></label><p>Tampon dolarsa okuma görevi hata verir; kayıtlar sessizce silinmez. Reddedilen batch sayısını Sistem sağlığı ekranından takip edin.</p></section><section className="settings-card settings-summary"><h3>Dosya özeti</h3><dl><dt>Master</dt><dd>{d.worker||'—'}</dd><dt>Cihaz kapsamı</dt><dd>{d.ids.length?d.ids.join(', '):'Tüm aktif cihazlar'}</dd><dt>Röle çıkışları</dt><dd>{d.gpio?`BCM ${d.pins}`:'Kapalı'}</dd><dt>Dijital girişler</dt><dd>{d.inputs?`BCM ${d.inputPins}`:'Kapalı'}</dd></dl>{validation&&<p className="settings-warning" role="alert">{validation}</p>}<button className="primary-button" disabled={busy||!!validation} onClick={()=>void download()}>{busy?'Hazırlanıyor…':'collector.json indir'}</button><p>Taslakta token tutulmaz. İndirilen dosya collector anahtarı içerir; master üzerinde sakla. Bu ekran donanım bağlantısını veya terminal eşleştirmesini otomatik değiştirmez.</p><p role="status">{message}</p></section></section>;
}
