import {useState} from 'react';
import type {Shape,Snapshot,Row} from './workspace';

export default function NodeSetup({node,data,parentHint,rpc,onCreated,onClose}:{node:Shape,data:Snapshot,parentHint:string|null,rpc:(p:string,m?:string,b?:Row)=>Promise<any>,onCreated:(key:string,name:string,parent:string)=>void,onClose:()=>void}){
 const [kind,setKind]=useState(node.type==='kiosk'?'DM':node.type==='transformer'?'TRAFO':node.type==='panel'?'ADP':'DEVICE');
 const [name,setName]=useState(node.name),[parent,setParent]=useState(parentHint||''),[power,setPower]=useState('1000'),[ratio,setRatio]=useState('34.5/0.4 kV'),[ip,setIp]=useState(''),[port,setPort]=useState('502'),[unit,setUnit]=useState('1'),[profile,setProfile]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const parentType=kind==='DM'?['SAHA']:kind==='TM'?['DM']:kind==='TRAFO'?['TM']:kind==='ADP'?['TRAFO']:['DM','TM','TRAFO','ADP'];
 const parents=data.nodes.filter(n=>parentType.includes(n.type)&&String(new Map(data.siteOf).get(n.key)??(n.type==='SAHA'?n.id:''))===String(data.selectedSite));
 const chosen=parents.some(n=>n.key===parent)?parent:parents.length===1?parents[0].key:'';
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');if(!chosen){setError('Besleyen öğeyi seç. Listede yoksa önce köşk → TM → trafo → AG pano sırasıyla eksik öğeyi ekle.');return;}setBusy(true);
  try{const parentId=Number(chosen.split(':')[1]);let body:Row={name:name.trim()};if(!body.name)throw Error('Öğeye bir ad ver.');
   if(kind==='DM')body={...body,saha_id:parentId,sira:0};if(kind==='TM')body={...body,dm_id:parentId,sira:0};if(kind==='TRAFO'){if(!(Number(power)>0)||!ratio.trim())throw Error('Trafo gücü pozitif olmalı; dönüşüm oranını gir.');body={...body,tm_id:parentId,guc_kva:Number(power),oran:ratio.trim()};}if(kind==='ADP')body={...body,trafo_id:parentId};
   if(kind==='DEVICE'){const p=data.config.profiles?.find(p=>String(p.id)===profile);if(!p)throw Error('Önce cihazın register haritasını içeren bir profil oluştur ve burada seç.');if(!p.surum&&!p.profil_surum)throw Error('Seçilen profilin sürümü boş. Cihaz profilleri ekranında sürümünü doldur.');if(!ip.trim()||!Number.isInteger(Number(port))||Number(port)<1||Number(port)>65535||!Number.isInteger(Number(unit))||Number(unit)<0||Number(unit)>247)throw Error('IP, 1–65535 arası port ve 0–247 arası Unit ID gir.');body={...body,ust_dugum_tipi:chosen.split(':')[0],ust_dugum_id:parentId,profil_id:Number(profile),profil_surum:p.surum??p.profil_surum,protokol:'MODBUS_TCP',ip:ip.trim(),port:Number(port),slave_id:Number(unit),aktif:true,bakim_modu:false,durum:'UNKNOWN'};}
   const result=await rpc(kind==='DEVICE'?'device':kind.toLowerCase(),'POST',body);const id=Number(typeof result==='object'?result.id:result);if(!Number.isSafeInteger(id)||id<=0)throw Error('Kayıt yanıtında ID yok. Yeniden göndermeden önce API kayıtlarını şemaya al ve kaydı kontrol et.');onCreated(`${kind}:${id}`,body.name,chosen);
  }catch(e){setError((e as Error).message+' Zaman aşımı varsa tekrar kaydetmeden önce kayıt listesini kontrol et.');}finally{setBusy(false);}
 }
 return <div className="node-setup-overlay"><form className="node-setup-dialog" onSubmit={save}><h2>Yeni öğeyi yapılandır</h2><p>API kaydı ve besleme bağlantısı birlikte hazırlanır.</p>{node.type==='kiosk'&&<label className="field"><span>Köşk türü</span><select value={kind} onChange={e=>{setKind(e.target.value);setParent('');}}><option value="DM">Dağıtım köşkü · saha girişi</option><option value="TM">TM · köşk çıkışındaki hücre</option></select></label>}<label className="field"><span>Ad</span><input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Besleyen öğe</span><select required value={chosen} onChange={e=>setParent(e.target.value)}><option value="">Seç</option>{parents.map(p=><option key={p.key} value={p.key}>{p.name} · {p.type}</option>)}</select></label>{kind==='TRAFO'&&<><label className="field"><span>Anma gücü · kVA</span><input type="number" required min="0.001" step="any" value={power} onChange={e=>setPower(e.target.value)}/></label><label className="field"><span>Gerilim oranı</span><input required value={ratio} onChange={e=>setRatio(e.target.value)}/></label></>}{kind==='DEVICE'&&<><label className="field"><span>Register profili</span><select required value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Profil seç</option>{data.config.profiles?.map(p=><option key={p.id} value={p.id}>{p.ad??p.name} · {p.surum}</option>)}</select></label><label className="field"><span>Modbus TCP IP / sunucu adı</span><input required value={ip} onChange={e=>setIp(e.target.value)} placeholder="192.168.1.20"/></label><div className="field-row"><label className="field"><span>Port</span><input required type="number" min="1" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label><label className="field"><span>Unit ID</span><input required type="number" min="0" max="247" value={unit} onChange={e=>setUnit(e.target.value)}/></label></div><p>Kaydettikten sonra seçtiğin profilden okuma grubu, register ve tag kurulum ekranı açılır. Ölçüm adresleri tahmin edilmez.</p></>}<p className="form-error" role="alert">{error}</p><div className="field-row"><button type="button" disabled={busy} className="outline-button" onClick={onClose}>Vazgeç · görsel olarak bırak</button><button className="primary-button" disabled={busy}>{busy?'Kaydediliyor…':'Kaydet ve bağla'}</button></div></form></div>;
}
